### ISSUE TITLE
idea: service that tracks chaos recipes

### ISSUE THREAD

**Issue by maximumstock** [maximumstock/poe-stash-indexer#60]
# Phase 1 - Base Consumer

- [ ] aggregate `StashRecord`s and build an internal state of the stashes
- [ ] supports serialization and deserialization of its internal state to resume stream consumption at a later point in time

At this point we should have a runnable service to test live.

# Phase 2 - Consumer Features eg. Chaos Recipe Calculator

- [ ] exposes some sort of HTTP API to request chaos recipes for an account name
  - this smells like an `async` project, but maybe not, lets see
  - one concern is how we manage continuous concurrent access to the aggregation store in the midst of handling updates and API requests 
- [ ] upon querying for a given account name, check the public stashes for appropriate item
- [ ] for the list of appropriate items, find the closest/a close set of subsets and return it (this is obviously the hardest part, it just has to be efficient though, not to block the rest of the aggregation, as there probably has to be a lock on the state)
